### ISSUE TITLE
Quick question on version tags

### ISSUE THREAD

**Issue by muppsy007** [heyday/silverstripe-wkhtml#10]
Hi there, 

I'm a bit confused about version tags in this module. I'd say it mostly stems from the Readme.md which says:

> A SilverStripe 3 version is available as ^2.x, and a SilverStripe 2.4 version is available as ^1.x.

As an aside, I had a look at the installation command on the Readme.md file, but it seems there is no 3.x tag at all.

> composer require "heyday/silverstripe-wkhtml:^3"

The only 2.x tag is 2.0.0-beta, which appears to be for SS4. 1.1.1 doesn't have any require dependencies on SS, but does have a require-dev dependency for SS 3.1.*@dev.

Am I right in assuming that the doc here has just fallen out of sync somewhere along the line and the latest version of this module for use with SS 3.7 would be 1.1.1 despite what it says?

**Comment by HJGreen** [comment]
Hi @muppsy007 

You're absolutely right, the version information in the README is incorrect.

Looking back through the tags, I would recommend:
- `1.1.1` for SilverStripe 3
- `2.0.0-beta` for SilverStripe 4

**Comment by muppsy007** [comment]
Thanks @HJGreen
