### ISSUE TITLE
Tag 2.0.0-beta1

### ISSUE THREAD

**Issue by sminnee** [heyday/silverstripe-wkhtml#7]
The dev-master version of this is needed for Silverstripe 4, but the latest tag is 1.1 from before this.

I've used this successfully on an internal project so I'd say it's at least good enough for a beta1 tag.

Right now I'm grabbing dev-master, which is a bit messy.

What's the appetite for doing a quick 2.0.0-beta1 tag on the current master head?

**Comment by sminnee** [comment]
@stevie-mayhew are you the person who would have the access to do this?

**Comment by bendubuisson** [comment]
Hey Sam I can do that for you

**Comment by bendubuisson** [comment]
https://github.com/heyday/silverstripe-wkhtml/releases/tag/2.0.0-beta1

**Comment by sminnee** [comment]
Awesome, thanks Ben :) I'll update my packagist version string now
